### ISSUE TITLE
PHP CLI requirements

### ISSUE THREAD

**Issue by ibakayoko** [orocrm/crm#131]
Hello,

Please how to fix the error below to be able to install OROCRM

Requirements validation for PHP CLI
```
Warning: date_default_timezone_get(): It is not safe to rely on the system's timezone settings. You are *required* to use the date.timezone setting or the date_default_timezone_set() function. In case you used any of those methods and you are still getting this warning, you most likely misspelled the timezone identifier. We selected the timezone 'UTC' for now, but please set date.timezone to select your timezone. in /Users/ixb/entreprise/orocrm/app/SymfonyRequirements.php on line 441

Warning: date_default_timezone_get(): It is not safe to rely on the system's timezone settings. You are *required* to use the date.timezone setting or the date_default_timezone_set() function. In case you used any of those methods and you are still getting this warning, you most likely misspelled the timezone identifier. We selected the timezone 'UTC' for now, but please set date.timezone to select your timezone. in /Users/ixb/entreprise/orocrm/app/SymfonyRequirements.php on line 442

Fatal error: Uncaught exception 'Symfony\Component\Intl\Exception\MethodArgumentValueNotImplementedException' with message 'The Symfony\Component\Intl\Collator\Collator::__construct() method's argument $locale value 'fr_FR' behavior is not implemented. Only the locale "en" is supported.  Please install the "intl" extension for full localization capabilities.' in /Users/ixb/entreprise/orocrm/vendor/symfony/symfony/src/Symfony/Component/Intl/Collator/Collator.php:80
Stack trace:
#0 /Users/ixb/entreprise/orocrm/app/SymfonyRequirements.php(619): Symfony\Component\Intl\Collator\Collator->__construct('fr_FR')
#1 /Users/ixb/entreprise/orocrm/app/OroRequirements.php(25): SymfonyRequirements->__construct()
#2 /Users/ixb/entreprise/orocrm/app/oro-check.php(6): OroRequirements->__construct()
#3 {main}
  thrown in /Users/ixb/entreprise/orocrm/vendor/symfony/symfony/src/Symfony/Component/Intl/Collator/Collator.php on line 80
```

**Comment by sergeyz** [comment]
Hi, @ibakayoko !

Please add date.timezone to php.ini with one of http://php.net/manual/en/timezones.php values

To get php.ini path please run `php -i | grep ini` from console

**Comment by ibakayoko** [comment]
I have this value set in the ini file.
I am using http://php-osx.liip.ch/ (latest 5.6 version) .
I have the following value in /usr/local/php5/php.d/99-liip-developer.ini 

date.timezone = "America/New_York"
date.default_latitude  = 40.7127
date.default_longitude =  74.0059

But i still get the same error on install.

phpinfo(); displays the following for date

```
date/time support 	enabled
"Olson" Timezone Database Version 	2015.5
Timezone Database 	internal
Default timezone 	America/New_York 
```

What else should i do?

```
l-c00008:web ixc$ php -v
PHP 5.6.11 (cli) (built: Jul 10 2015 21:46:48) 
Copyright (c) 1997-2015 The PHP Group
Zend Engine v2.6.0, Copyright (c) 1998-2015 Zend Technologies
    with Zend OPcache v7.0.6-dev, Copyright (c) 1999-2015, by Zend Technologies
```

Thank you

**Comment by ibakayoko** [comment]
I was finally able to proceed with the install on command line by running

```
php app/console oro:install --force --timeout=0 
```

**Comment by adyassine** [comment]
Thanks @ibakayoko php app/console oro:install --force --timeout=0  works fine !
