### ISSUE TITLE
Error on install on centos 7.2.1511

### ISSUE THREAD

**Issue by vfbsilva** [orocrm/crm#155]
Folks seems some files are missing on the commit from 1.9.0. I have an open discussion on the [forums](http://www.orocrm.com/forums/topic/install-fails-on-centos-7-2-1511)
```
[Tue Mar 01 15:10:06.627851 2016] [:error] [pid 24592] [client 10.32.83.51:47569] PHP Warning:  require(/var/www/html/crm-application/app/../vendor/autoload.php): failed to open stream: No such file or directory in /var/www/html/crm-application/app/autoload.php on line 5
[Tue Mar 01 15:10:06.627940 2016] [:error] [pid 24592] [client 10.32.83.51:47569] PHP Fatal error:  require(): Failed opening required '/var/www/html/crm-application/app/../vendor/autoload.php' (include_path='.:/usr/share/pear:/usr/share/php') in /var/www/html/crm-application/app/autoload.php on line 5
```
I was able to find the mentioned files in other versions of the package but just adding them did not solve the problem.

**Comment by rodolfobandeira** [comment]
@vfbsilva answered you on forum. 

It's compaining that you don't have `/var/www/html/crm-application/vendor/autoload.php` which must be  generated automatically when you run `composer install`

**Comment by vfbsilva** [comment]
@rodolfobandeira I have it in many places:
`

In many places:
./html/orocrm/app/autoload.php
./html/orocrm/vendor/zendframework/zend-stdlib/src/compatibility/autoload.php
./html/orocrm/vendor/autoload.php
./html/orocrm/vendor/symfony/symfony/src/Symfony/Component/Intl/Resources/bin/autoload.php
./html/crm-application/app/autoload.php
./html/orocrm/app/autoload.php
./html/orocrm/vendor/zendframework/zend-stdlib/src/compatibility/autoload.php
./html/orocrm/vendor/autoload.php
./html/orocrm/vendor/symfony/symfony/src/Symfony/Component/Intl/Resources/bin/autoload.php
./html/crm-application/app/autoload.php
`

All owned by the apache user.

**Comment by mbessolov** [comment]
If I understand you setup correctly `/var/www/html/orocrm` and `/var/www/html/crm-application` are two different installations.
And it seems that you have never run  `composer install` command inside the `/var/www/html/crm-application` folder.

**Comment by vfbsilva** [comment]
@mbessolov  the files are just copies of the same install sorry I forgot to supress it from the ls output this was due a suggestion from a guy [here](http://www.orocrm.com/forums/topic/install-fails-on-centos-7-2-1511/page/2/#post-16765) on the support forum. 

At the official docs listed here it does not explicitly asks me to run composer install inside the app folder. Instead it asks for an update there. According to [this](http://www.orocrm.com/documentation/index/current/book/installation). 
Oki running the command inside the folder yelded another (better) error.
`php -dmemory_limit=4G /bin/composer update`

The following exception is caused by a lack of memory and not having swap configured
Check https://getcomposer.org/doc/articles/troubleshooting.md#proc-open-fork-failed-errors for details

PHP Fatal error:  Uncaught exception 'ErrorException' with message 'proc_open(): fork failed - Cannot allocate memory' in phar:///usr/bin/composer/vendor/symfony/console/Application.php:954
Stack trace:
#0 [internal function]: Composer\Util\ErrorHandler::handle(2, 'proc_open(): fo...', 'phar:///usr/bin...', 954, Array)
#1 phar:///usr/bin/composer/vendor/symfony/console/Application.php(954): proc_open('stty -a | grep ...', Array, NULL, NULL, NULL, Array)
#2 phar:///usr/bin/composer/vendor/symfony/console/Application.php(754): Symfony\Component\Console\Application->getSttyColumns()
#3 phar:///usr/bin/composer/vendor/symfony/console/Application.php(715): Symfony\Component\Console\Application->getTerminalDimensions()
#4 phar:///usr/bin/composer/vendor/symfony/console/Application.php(648): Symfony\Component\Console\Application->getTerminalWidth()
#5 phar:///usr/bin/composer/vendor/symfony/console/Application.php(130): Symfony\Component\Console\Application->renderException(Object(ErrorException), Object(Symfony\Component\Console\Out in phar:///usr/bin/composer/vendor/symfony/console/Application.php on line 954

Fatal error: Uncaught exception 'ErrorException' with message 'proc_open(): fork failed - Cannot allocate memory' in phar:///usr/bin/composer/vendor/symfony/console/Application.php:954
Stack trace:
#0 [internal function]: Composer\Util\ErrorHandler::handle(2, 'proc_open(): fo...', 'phar:///usr/bin...', 954, Array)
#1 phar:///usr/bin/composer/vendor/symfony/console/Application.php(954): proc_open('stty -a | grep ...', Array, NULL, NULL, NULL, Array)
#2 phar:///usr/bin/composer/vendor/symfony/console/Application.php(754): Symfony\Component\Console\Application->getSttyColumns()
#3 phar:///usr/bin/composer/vendor/symfony/console/Application.php(715): Symfony\Component\Console\Application->getTerminalDimensions()
#4 phar:///usr/bin/composer/vendor/symfony/console/Application.php(648): Symfony\Component\Console\Application->getTerminalWidth()
#5 phar:///usr/bin/composer/vendor/symfony/console/Application.php(130): Symfony\Component\Console\Application->renderException(Object(ErrorException), Object(Symfony\Component\Console\Out in phar:///usr/bin/composer/vendor/symfony/console/Application.php on line 954

**Comment by mbessolov** [comment]
According to the installation instructions at http://www.orocrm.com/documentation/index/current/book/installation here is the list of what has to be done to install the latest version of OroCRM:

```
cd /var/www
git clone -b 1.9.0 https://github.com/orocrm/platform-application.git orocrm-1.9.0
cd orocrm-1.9.0
composer install
```

or, if you are using a downloaded archive instead of GitHub:

```
# extract the contents of the archive into orocrm-1.9.0 directory,
# after the extraction the orocrm-1.9.0 directory should have app, src and vendor folders, and a number of files.
cd orocrm-1.9.0
composer install
```

**Comment by vfbsilva** [comment]
Oki done as suggested. Still a problem:

> root@lojacrmdes crm-application]# php -dmemory_limit=2G /bin/composer -vvv --no-dev install
Reading ./composer.json
Loading config file /root/.composer/config.json
Loading config file /root/.composer/auth.json
Loading config file ./composer.json
Checking CA file /etc/pki/ca-trust/extracted/pem/tls-ca-bundle.pem
Executing command (/var/www/html/crm-application): git branch --no-color --no-abbrev -v
Executing command (/var/www/html/crm-application): git describe --exact-match --tags
Failed to initialize global composer: Composer could not find the config file: /root/.composer/composer.json
To initialize a project, please create a composer.json file as described in the https://getcomposer.org/ "Getting Started" section
Reading /var/www/html/crm-application/vendor/composer/installed.json
Loading plugin ComponentInstaller\ComponentInstallerPlugin
Reading ./composer.lock
Loading composer repositories with package information
Installing dependencies from lock file
Reading ./composer.lock
Warning: The lock file is not up to date with the latest changes in composer.json. You may be getting outdated dependencies. Run update to update them.
Analyzed 273 packages to resolve dependencies
Analyzed 847 rules to resolve dependencies
Nothing to install or update
Generating autoload files
> post-autoload-dump: ComponentInstaller\Installer::postAutoloadDump
Compiling component files
> post-install-cmd: Incenteev\ParameterHandler\ScriptHandler::buildParameters
Updating the "app/config/parameters.yml" file
> post-install-cmd: Sensio\Bundle\DistributionBundle\Composer\ScriptHandler::buildBootstrap
> post-install-cmd: Sensio\Bundle\DistributionBundle\Composer\ScriptHandler::installRequirementsFile
> post-install-cmd: Oro\Bundle\InstallerBundle\Composer\ScriptHandler::setPermissions
> post-install-cmd: Oro\Bundle\InstallerBundle\Composer\ScriptHandler::installAssets
> post-install-cmd: Oro\Bundle\InstallerBundle\Composer\ScriptHandler::setAssetsVersion
Initializing the "assets_version_strategy" parameter
[root@lojacrmdes crm-application]# service httpd restart
Redirecting to /bin/systemctl restart  httpd.service

> 
Same behavior.

**Comment by rodolfobandeira** [comment]
I would remove this folder and reinstall everything again following the instructions they gave to you.

**Comment by vfbsilva** [comment]
I've done it. Started with a folder from scratch same result.

**Comment by sergeyz** [comment]
looks like database contains data from previous installation attempts
```
Process migrations...
  > Oro\Bundle\EntityExtendBundle\Migration\LoadEntityConfigStateMigration
```

please drop and recreate database before install

**Comment by vfbsilva** [comment]
@sergeyz I've selected on the gui installer to do such thing I've dropped the database manually now and it did work. So I think part of the problem was that the guy installer is not dropping the DB. Maybe it could pop a bigger warning?

**Comment by sergeyz** [comment]
Will check drop database for gui installer, thanks for report!

**Comment by woei66** [comment]
@sergeyz
Since your are experter of oro-crom, you have enough experience and identify the root cause is "database contains data from previous installation"
If the **database contains old data of previous installation** and it will cause the installation failure, please add the problem **detection** or **warning message** at the console mode and tell users how to do.
Or, it should **detect** the problem and **stop** the installation and ask users drop the database and displays warning/error messages to users and ask them if they want to drop previous database to continue ..

It's important that without these information and experiences that will **waste** your time and our time to figure out the root cause.

I am Magento2 users and I faced the same case.
This problem should be fixed permanently.

**Comment by artml** [comment]
@woei66 I have created a ticket in our backlog, but it's hard to say now when we will be able to provide a permanent fix. I am marking this as open for community contribution for now, and will change the status as soon as we'll schedule the fix for some version. I've also updated the issue title to make it more clear.

Thanks for your contribution!
