### ISSUE TITLE
Problem after adding a new entity and trying to import contacts

### ISSUE THREAD

**Issue by shariukas** [orocrm/crm#191]
Hello, i have tried to add couple new entities on Users module and tried to import users from CSV. Import fails and Symfony gets an error: 

batch.ERROR: Encountered an error executing the step: A new entity was found through the relationship 'OroCRM\Bundle\ContactBundle\Entity\Contact#CIty' that was not configured to cascade persist operations for entity: Vilnius. To solve this issue: Either explicitly call EntityManager#persist() on this unknown entity or configure cascade persist  this association in the mapping for example @ManyToOne(..,cascade={"persist"}). [] []

**Comment by mkudelya** [comment]
@shariukas can you give me a list with our entities and relations between them?
In simple words, how you modify oro-crm unlike a clean system.
Also i recommend you read [the manual](http://docs.doctrine-project.org/en/latest/reference/working-with-associations.html#transitive-persistence-cascade-operations) about cascade operations.

**Comment by sagikazarmark** [comment]
The same happened with me with a custom platform application:

```
Encountered an error executing the step: A new entity was found through the relationship 'Oro\Bundle\DataAuditBundle\Entity\AbstractAudit#organization' that was not configured to cascade persist operations for entity: TSTC. To solve this issue: Either explicitly call EntityManager#persist() on this unknown entity or configure cascade persist  this association in the mapping for example @ManyToOne(..,cascade={"persist"}). [] []
```

Interestingly the import works fine from console. I remember that the organization storage in the session had some bugs, which might have been solved in 1.10?

Platform version: 1.9.2

**Comment by mkudelya** [comment]
@sagikazarmark can you show me the entity source code and more detailed error description ?
Maybe it was because you run UI and console in different environment with different cache?

**Comment by sagikazarmark** [comment]
No, both ran in prod env, using the same cache.

Entity and import/export config: https://gist.github.com/sagikazarmark/6778b635e84cc19fc902fc9c27aff417

Unfortunately, I don't really know what other error description I could give. Here are the steps:

1. Import fil
2. Import validation runs
3. Import stats are shown (what to add, what to replace)
4. Click import
5. Error message shown (failed to import or something like that), the above error pasted into the logs

The error persists in a completely new install as well.

**Comment by sagikazarmark** [comment]
Update: the same problem happens on 1.10.0 too

**Comment by mkudelya** [comment]
Can you provide me also schema migration and import file for your Promoter entity ?

**Comment by sagikazarmark** [comment]
Updated gist

**Comment by sagikazarmark** [comment]
Strange thing: importing works perfectly with ~10 entries (probably with more too). But it can't handle all entries in the example file

**Comment by mkudelya** [comment]
@sagikazarmark I will report you my investigation result.

**Comment by sagikazarmark** [comment]
Awesome, thank you very much.

**Comment by mkudelya** [comment]
I have installed fresh 1.9.2 tag (and also master) and have tested our case. I changed only path to files. Everything is working.

PHP 5.5.36
MySQL Server version: 5.5.48

> Encountered an error executing the step: A new entity was found through the relationship 'Oro\Bundle\DataAuditBundle\Entity\AbstractAudit#organization' that was not configured to cascade persist operations for entity: TSTC

Interesting, what is TSTC entity ?

**Comment by sagikazarmark** [comment]
TSTC is the name of the organization

**Comment by sagikazarmark** [comment]
Hm, found something new in the `akeneo_batch_step_execution` table:


```
#0 /app/vendor/doctrine/orm/lib/Doctrine/ORM/UnitOfWork.php(856): Doctrine\ORM\ORMInvalidArgumentException::newEntityFoundThroughRelationship(Array, Object(Proxies\__CG__\Oro\Bundle\OrganizationBundle\Entity\Organization))
#1 /app/vendor/doctrine/orm/lib/Doctrine/ORM/UnitOfWork.php(741): Doctrine\ORM\UnitOfWork->computeAssociationChanges(Array, Object(Proxies\__CG__\Oro\Bundle\OrganizationBundle\Entity\Organization))
#2 /app/vendor/oro/platform/src/Oro/Bundle/DataAuditBundle/Loggable/LoggableManager.php(552): Doctrine\ORM\UnitOfWork->computeChangeSet(Object(Doctrine\ORM\Mapping\ClassMetadata), Object(Oro\Bundle\DataAuditBundle\Entity\Audit))
#3 /app/vendor/oro/platform/src/Oro/Bundle/DataAuditBundle/Loggable/LoggableManager.php(190): Oro\Bundle\DataAuditBundle\Loggable\LoggableManager->createLogEntity('create', Object(PromoBundle\Entity\Promoter))
#4 /app/vendor/oro/platform/src/Oro/Bundle/DataAuditBundle/EventListener/EntityListener.php(57): Oro\Bundle\DataAuditBundle\Loggable\LoggableManager->handleLoggable(Object(Oro\Bundle\EntityBundle\ORM\OroEntityManager))
#5 /app/var/cache/dev/appDevDebugProjectContainer.php(75171): Oro\Bundle\DataAuditBundle\EventListener\EntityListener->onFlush(Object(Doctrine\ORM\Event\OnFlushEventArgs))
#6 /app/vendor/symfony/symfony/src/Symfony/Bridge/Doctrine/ContainerAwareEventManager.php(63): OroBundleDataAuditBundleEventListenerEntityListener_000000005dc1959b0000000026f28cdfca32f400d20e5e139b6db4c6ce0c520a->onFlush(Object(Doctrine\ORM\Event\OnFlushEventArgs))
#7 /app/vendor/oro/platform/src/Oro/Bundle/EntityBundle/Event/OroEventManager.php(48): Symfony\Bridge\Doctrine\ContainerAwareEventManager->dispatchEvent('onFlush', Object(Doctrine\ORM\Event\OnFlushEventArgs))
#8 /app/vendor/doctrine/orm/lib/Doctrine/ORM/UnitOfWork.php(3306): Oro\Bundle\EntityBundle\Event\OroEventManager->dispatchEvent('onFlush', Object(Doctrine\ORM\Event\OnFlushEventArgs))
#9 /app/vendor/doctrine/orm/lib/Doctrine/ORM/UnitOfWork.php(367): Doctrine\ORM\UnitOfWork->dispatchOnFlushEvent()
#10 /app/var/cache/dev/classes.php(8220): Doctrine\ORM\UnitOfWork->commit(NULL)
#11 /app/var/cache/dev/classes.php(8600): Doctrine\ORM\EntityManager->flush(NULL)
#12 /app/var/cache/dev/jms_diextra/doctrine/EntityManager_57b9c4965bbd0.php(165): Oro\Bundle\EntityBundle\ORM\OroEntityManager->flush(NULL)
#13 /app/vendor/oro/platform/src/Oro/Bundle/ImportExportBundle/Writer/EntityWriter.php(61): EntityManager57b9c4965bbd0_546a8d27f194334ee012bfe64f629947b07e4919\__CG__\Doctrine\ORM\EntityManager->flush()
#14 /app/vendor/oro/platform/src/Oro/Bundle/BatchBundle/Step/StepExecutor.php(207): Oro\Bundle\ImportExportBundle\Writer\EntityWriter->write(Array)
#15 /app/vendor/oro/platform/src/Oro/Bundle/BatchBundle/Step/StepExecutor.php(171): Oro\Bundle\BatchBundle\Step\StepExecutor->write(Array, Object(Oro\Bundle\BatchBundle\Step\ItemStep))
#16 /app/vendor/oro/platform/src/Oro/Bundle/BatchBundle/Step/ItemStep.php(33): Oro\Bundle\BatchBundle\Step\StepExecutor->execute(Object(Oro\Bundle\BatchBundle\Step\ItemStep))
#17 /app/vendor/akeneo/batch-bundle/Akeneo/Bundle/BatchBundle/Step/AbstractStep.php(162): Oro\Bundle\BatchBundle\Step\ItemStep->doExecute(Object(Akeneo\Bundle\BatchBundle\Entity\StepExecution))
#18 /app/vendor/akeneo/batch-bundle/Akeneo/Bundle/BatchBundle/Job/Job.php(401): Akeneo\Bundle\BatchBundle\Step\AbstractStep->execute(Object(Akeneo\Bundle\BatchBundle\Entity\StepExecution))
#19 /app/vendor/akeneo/batch-bundle/Akeneo/Bundle/BatchBundle/Job/Job.php(361): Akeneo\Bundle\BatchBundle\Job\Job->handleStep(Object(Oro\Bundle\BatchBundle\Step\ItemStep), Object(Akeneo\Bundle\BatchBundle\Entity\JobExecution))
#20 /app/vendor/akeneo/batch-bundle/Akeneo/Bundle/BatchBundle/Job/Job.php(296): Akeneo\Bundle\BatchBundle\Job\Job->doExecute(Object(Akeneo\Bundle\BatchBundle\Entity\JobExecution))
#21 /app/vendor/oro/platform/src/Oro/Bundle/ImportExportBundle/Job/JobExecutor.php(125): Akeneo\Bundle\BatchBundle\Job\Job->execute(Object(Akeneo\Bundle\BatchBundle\Entity\JobExecution))
#22 /app/vendor/oro/platform/src/Oro/Bundle/ImportExportBundle/Job/JobExecutor.php(98): Oro\Bundle\ImportExportBundle\Job\JobExecutor->doJob(Object(Akeneo\Bundle\BatchBundle\Entity\JobInstance), Object(Akeneo\Bundle\BatchBundle\Entity\JobExecution))
#23 /app/var/cache/dev/appDevDebugProjectContainer.php(76721): Oro\Bundle\ImportExportBundle\Job\JobExecutor->executeJob('import', 'entity_import_f...', Array)
#24 /app/vendor/oro/platform/src/Oro/Bundle/ImportExportBundle/Handler/AbstractImportHandler.php(100): OroBundleImportExportBundleJobJobExecutor_000000005dc198130000000026f28cdfca32f400d20e5e139b6db4c6ce0c520a->executeJob('import', 'entity_import_f...', Array)
#25 /app/vendor/oro/platform/src/Oro/Bundle/ImportExportBundle/Handler/HttpImportHandler.php(120): Oro\Bundle\ImportExportBundle\Handler\AbstractImportHandler->executeJob('entity_import_f...', 'promo.promoter....', 'csv', Array, 'promo.promoter....')
#26 /app/var/cache/dev/appDevDebugProjectContainer.php(77011): Oro\Bundle\ImportExportBundle\Handler\HttpImportHandler->handleImport('entity_import_f...', 'promo.promoter....', 'csv', 'promo.promoter....', Array)
#27 /app/vendor/oro/platform/src/Oro/Bundle/ImportExportBundle/Controller/ImportExportController.php(122): OroBundleImportExportBundleHandlerHttpImportHandler_000000005dc1811e0000000026f28cdfca32f400d20e5e139b6db4c6ce0c520a->handleImport('entity_import_f...', 'promo.promoter....', 'csv', NULL, Array)
#28 [internal function]: Oro\Bundle\ImportExportBundle\Controller\ImportExportController->importProcessAction('promo.promoter....')
#29 /app/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/HttpKernel.php(144): call_user_func_array(Array, Array)
#30 /app/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/HttpKernel.php(64): Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object(Symfony\Component\HttpFoundation\Request), 1)
#31 /app/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/DependencyInjection/ContainerAwareHttpKernel.php(69): Symfony\Component\HttpKernel\HttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true)
#32 /app/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Kernel.php(185): Symfony\Component\HttpKernel\DependencyInjection\ContainerAwareHttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true)
#33 /app/web/app_dev.php(30): Symfony\Component\HttpKernel\Kernel->handle(Object(Symfony\Component\HttpFoundation\Request))
#34 {main}
```

**Comment by sagikazarmark** [comment]
This line made me think:

> #12 /app/var/cache/dev/jms_diextra/doctrine/EntityManager_57b9c4965bbd0.php(165): Oro\Bundle\EntityBundle\ORM\OroEntityManager->flush(NULL)

So I removed JMS DI Extra bundle and now it works.

**Comment by mkudelya** [comment]
Does import fully works?

**Comment by sagikazarmark** [comment]
Yes, it does.

**Comment by mkudelya** [comment]
fine :)

**Comment by shariukas** [comment]
Could you pls stop spamming me?

**Comment by sagikazarmark** [comment]
Noone was spamming you @shariukas, if you don't want to get notifications, I suggest you clicking the unsubscribe button.

------------------------------------------------------------------------------------------------------>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>

**Comment by artml** [comment]
Okay, I consider this issue has been fixed.
