### ISSUE TITLE
Serialization of 'Closure' is not allowed - /app_dev.php/task/update/1

### ISSUE THREAD

**Issue by markusrothenbacher** [orocrm/crm#223]
I use OroCrm 1.10.6, all Packages are up to date (run a composer update), all caches cleared, migrations run fine, also oro:composer:update runs clean.

But with in dev mode (app_dev.php) some URLs cause an error (in Production they work fine.)
When I surf for example to /app_dev.php/task/update/1 the symfony profiler thows the following error:
```
<b>Fatal error</b>:  Uncaught Exception: Serialization of 'Closure' is not allowed in /var/www/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/DataCollector/DataCollector.php:35
Stack trace:
#0 [internal function]: SplObjectStorage-&gt;serialize()
#1 /var/www/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/DataCollector/DataCollector.php(35): serialize(Array)
#2 [internal function]: Symfony\Component\HttpKernel\DataCollector\DataCollector-&gt;serialize()
#3 /var/www/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Profiler/FileProfilerStorage.php(159): serialize(Array)
#4 /var/www/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Profiler/Profiler.php(120): Symfony\Component\HttpKernel\Profiler\FileProfilerStorage-&gt;write(Object(Symfony\Component\HttpKernel\Profiler\Profile))
#5 /var/www/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/EventListener/ProfilerListener.php(158): Symfony\Component\HttpKernel\Profiler\Profiler-&gt;saveProfile(Object(Symfony\Component\HttpKernel\Profiler\Profile))
#6 [internal in <b>/var/www/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/DataCollector/DataCollector.php</b> on line <b>35</b><br />
```
The update page itself works as expected, but the web profiler does not show.

**Comment by mkudelya** [comment]
Hi @markusrothenbacher 

Thank you for your issue. I have reported it.

**Comment by sbani** [comment]
Hi @mkudelya, reported to whom? Internal Jira?

**Comment by artml** [comment]
@sbani yes :) sorry if the wording has been confusing, we are non-native English speakers and this happens sometimes.

We have added this bug to our internal JIRA and will work on the fix. Hard to say _when_ atm, so I will mark this bug as open for contribution and will update its labels as soon as it'll get into the dev pipeline.
